name: inventory
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_runner: ^2.1.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.2
  flutter_modular: ^4.1.1
  mobx: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  modular_test: ^1.0.1+1

flutter:

  uses-material-design: true
